import streamlit as st
import pandas as pd
import io

# Raw data as string (tab-separated)
raw_data = """Summary	Issue key	GET Ids	Parent id	Customer	Defect Type	Defect  Found  in Release	Fixed in Release	Severity	Safe escape defects	Defect Category	Defect_Subcategories 	Status	Project key	Project name	Priority	Month reported	Execution details	TC Num	Automation Status	Root case issue	Preventive Steps taken	Defect Affect Version	Summary of Actions	Completion Status	Comments	Actions	Modules
Engineering Analysis for TEC-414761 ELM Internal (Omega II Network): Error in Office Companion - Production Environment	TEC-416125	GET-42690	TEC-414761	Internal Sales team	Application	24.1.13	None	SEV-3	Yes	Non-Reproducible on lower environments	Client specific configuration	Backlog	TEC	Technical Operations	High	Jan-25	Executed in 23.2.2	TC-1782	Automated	When attempting to review recently created invoices in Office Companion on the Omega II network in Production, users encounter the error: "You do not have access to this object. Please contact Admin to get permission." This occurs specifically for invoices created in December 2024 (e.g., 24-DEC-ACK-TEST, 24-DEC-ACK-039, 24-DEC-ACK-022, and 24-DEC-ACK-008). Older invoices do not exhibit this issue.	Action: OC cases related to adjustments should be part of regression suite		`Test Case exists. Script will be modified as per new code changes.	Awaiting Code fix	Issue was reproduced in Production QA Network	Not prioritized yet, In backlog currently	Office Companion
Engineering Analysis for TEC-414871 - T360 Performance Lag "Invoices Awaiting My Review" Page	TEC-416175	GET-42691	TEC-414871	Gallagher Bassett	Application - Performance	24.1.13	None	SEV-3	No	Non-Reproducible on lower environments	Non-Reproducible on lower environments	Backlog	TEC	Technical Operations	Medium	Jan-25	Executed in all releases	TC-3944	Automated	Client mentioned  The users logged in successfully, but when he clicks on Invoices Awaiting My Review, the page spins for over 10 minutes before either eventually loading or returning a timeout error.	Action: Invoice awaiting my review related checks should be part of regression suite		`Test Case exists. Script will be modified as per new code changes.	Awaiting Code fix		"Prioritized and assigned to Mavericks team
https://Code.azure.com/GRC-ELM/T360/_build/results?buildId=401363&view=ms.vss-test-web.build-test-results-tab"	Invoicing
Engineering Analysis For TEC-415071 - Chubb Group Claims: Duplicated Appeal Amounts again	TEC-416315	GET-42692	TEC-415071	Chubb Group Claims	Application - Not Reproduced	24.1.13	None	SEV-3	Yes	Non-Reproducible on lower environments	Non-Reproducible on lower environments	Backlog	TEC	Technical Operations	Medium	Jan-25	Executed in all releases	TC-4604	Automated	Client mentioned that System ID 49232666 received automatic adjustments upon submission and review. The firm appealed each adjusted item for exactly the adjustment amount, and when the appeals were approved the amounts were duplicated. The invoice now has a total of $215 extra billed across 8 separate line items.	Action: TPA appeal cases should be part of regression suite.		`Test Case exists. Script will be modified as per new code changes.	Awaiting Code fix	Reassigned to CS team as issue is not reproducible in lower env.	"Not prioritized yet, In backlog currently
https://Code.azure.com/GRC-ELM/T360/_build/results?buildId=396011&view=ms.vss-test-web.build-test-results-tab"	Invoicing
Engineering Analysis for TEC-415225 AJG: Payment Processing (via the UI and NOT payment app) failing since 12/30/2024	TEC-416040	GET-42689	TEC-415225	AJG	Application - Not Reproduced	24.1.13	None	SEV-3	Yes	Client specific data	Client specific configuration	Backlog	TEC	Technical Operations	Medium	Jan-25	Executed in all releases	TC-11808	Manual	"Starting on 12/30/2024, the AJG Processed Invoice File is failing during execution due to a System.ArgumentException. The error message specifies that ""An entry with the same key already exists,"" which typically suggests that there is a duplicate entry in a collection or dictionary where each key must be unique.

As a result of this exception, AJG is unable to process invoices, and this issue has led to missed payment processing for three consecutive runs"	Action: Network discount cases are part of smoke test suite every release		Test Case exists. Automation not possible as invoice id needs to pass in text file each run for Fee app in VM to execute.	Awaiting analysis on client configuration and Code fix		Not prioritized yet, In backlog currently	Payment Processing
Engineering Analysis for TEC-416812 Worley: Manual Invoices Submit as Paid Error Happening Since June 2023	TEC-418354	GET-43863	TEC-416812	Worley International	Application	24.1.13	T360 25.2.3	SEV-3	Yes	Testing Coverage	Test scenario unavailable	Complete	TEC	Technical Operations	Medium	Jan-25	Executed in 25.2.3	"TC-17787, TC-17640, TC-17783 , TC-17782, TC-17785, TC-17786, TC-17784, TC-17783, TC-17788

"	Automated	When users click the "Submit As Paid" option on the Invoice Summary page and select an invoice paid date, they encounter an internal application error.	Action: Invoice with multiple actions should be part of regression suite.		Test case written .Automation Completed. Pipeline Established	Completed	Assigned to CS Team - Regression cases - TC-4453 , TC-4457, 4494, 4452	"Prioritized and fixed as part of 25.2.3 
https://dev.azure.com/GRC-ELM/T360/_build/results?buildId=510947&view=ms.vss-test-web.build-test-results-tab"	Invoicing
Engineering Analysis for TEC-416937 All Clients: Update T360 Help Re: Permissions Directory	TEC-417484		TEC-416937	All Clients	Application	24.1.13	None	SEV-3	No	Requirement Coverage	Missing Requirements	Complete	TEC	Technical Operations	Medium	Jan-25			Not Automated	The "Permissions Directory" article in T360 Help is outdated and lacks at least two services - Allocated Claim and SIR permissions. An update is needed to include these and any other recently added permissions.			"PO assigned to Steve Clark for article correction
"	Completed		"Article correction completed by Steve
T360 help that the two missing permissions directories (Allocated Claims and SIR) are now present."	Help
Engineering Analysis for TEC-414519 AJG: [Office Companion] For certain items, selecting Cancel All does not cancel uploads	TEC-419541	GET-44224	TEC-414519	AJG	Application	24.1.13	None	SEV-4	Yes	Testing Coverage	Test Case Execution	Backlog	TEC	Technical Operations	Medium	Feb-25	Executed in all releases	TC-6153	Automated	User is unable to cancel the email uploads by clicking on cancel all.	Action: OC email document specific cases are part of regression suite		`Test Case exists. Script will be modified as per new code changes.	Awaiting Code fix		Not prioritized yet, In backlog currently	Office Companion
Engineering Analysis : LBA: LSA Functionality not working consistently	TEC-420293	GET-44362	TEC-416837	ELM Solutions Internal	Application	24.1.13	25.2.2	SEV-3	Yes	Testing Coverage	Test Case Execution	Complete	TEC	Technical Operations	Medium	Feb-25	Executed in 24.1.1 , 25.2.2 , 25.2.5	TC-13054 , TC-12486	Automated	"The LBA team reports the following behavior with the new LSA functionality for their reviewers:

Errors in LSA Functionality in Q360:

Unpredictable Behavior: Users experience inconsistency when typing the rule numbers, where the drop-down to confirm and populate the rule sometimes does not appear. This prevents any use of the functionality to populate a reason and narrative.
This issue occurs randomly and can start or stop without a clear cause, but it most often seems to occur when a user tries making an adjustment for the first time in a session."	Action: LSA test cases should be part of regression automation suite.		Test case exists. Automation Completed. Pipeline is established. 	Completed		Prioritized and released as part of 25.2.2	LSA
Engineering Analysis for TEC-418461 Outlook Office Companion Not Working w/T360	TEC-421827	GET-45846	TEC-418461	Farmers Group, Inc. Corporate Legal Office	Application - Not Reproduced	24.1.15	None	SEV-3	Yes	Client specific data	Client specific data	Complete	TEC	Technical Operations	Medium	Feb-25	Executed in all releases	TC-6547 	Automated	"Farmers Corp Legal user Nicole Seeley (Login ID: Z70058962) is experiencing an issue where dragging emails from Office Companion to a matter in T360 causes the page to hang, preventing the email from being imported. This issue occurs across all matters, including Matter #25000005 (Distribution Review—General 2025).

Other Farmers Corp legal users are not experiencing this issue. Nicole has attempted to uninstall and reinstall the Office Companion plugin, but the problem persists."	Action: Office companion cases are already part of regression automation suite.		Test case exists.	Completed	This issue is similar to GET-45893 but, according to Tech Ops has different behaviors so separate cases were created.	Case is closed by PO with Not Needed resolution.	Office Companion
Engineering Analysis for TEC-419124 All Clients: Workflow diagram on workflow instance details page is unusable	TEC-420007	GET-44525	TEC-419124	Westfield Insurance Company	Application	24.1.15	25.2.3	SEV-3	Yes	Testing Coverage	Test case Non-Existent	Complete	TEC	Technical Operations	Medium	Feb-25	Executed in 25.2.1 , 25.2.2	TC-17394,TC-17395	Automated	Westfield Insurance has raised concerns about the workflow diagram not displaying correctly on the WorkflowDefinitionDetailPage.aspx and WorkflowInstanceDetailPage.aspx pages. The diagram only appears in the bottom fourth of the page, even when the other headers are collapsed. This issue has been present in both the old and new user interfaces and affects both Google Chrome and Microsoft Edge. This makes it difficult to troubleshoot workflows, especially when a step is repeating or when specific steps need to be inspected.	Action: Workflow cases should be part of regression suite		`Test Case is written. Automation completed. Pipeline yet to established	Completed		Prioritized and released as part of 25.2.2	Dynamic Workflow
Engineering Analysis for TEC-419952 RBC: Legal Entity Search Field (Search All Matters)	TEC-421546	GET-45847	TEC-419952	RBC	Application - Not Reproduced	24.1.15	None	SEV-3	Yes	Client specific data	Client specific data	Complete	TEC	Technical Operations	Medium	Feb-25	Executed in all releases	TC-20840, TC-20838, TC-40835, TC-20837, TC-20836, TC-20834	Automated	"For a specific matter, when user search with matter name and legal entity with quotes.
the matter is not displayed."	Action: `Dynamic field filter searches in Search all matters page should be part of regression automation suite.		"Test case exists. Automation Completed. Pipeline is established. 
"	Completed		Prioritized and released as part of 25.3.4	Quick Search
[RCA] - Phoenix Afternoon Run Failed to Start Feb 11 2025	TEC-420669		TEC-420454	ELM Solutions Internal	Infrastructure	24.1.15	None	SEV-3	No	External Issues	External issue	Complete	TEC	Technical Operations	High	Feb-25	Executed in all releases	TC-4325	Automated	Phoenix afternoon job did not run on time and it impacted the clients reports to run with latest data.			"Test case exists. Automation Completed. Pipeline is established. 
"	Completed		"Prioritized and completed by SRE team 
https://dev.azure.com/GRC-ELM/T360/_build/results?buildId=433135&view=ms.vss-test-web.build-test-results-tab"	Phoenix
[RCA] - T360 NA - February 13 2025 - T360 North America is Down - Internal Update - 1	TEC-420912	GET-44820	TEC-420728	All NA Clients	Application - Performance	25.1.1	T360 25.1.1	SEV-1	Yes	Incomplete Impact Analysis	Incomplete Impact Analysis	Complete	TEC	Technical Operations	Highest	Feb-25	Executed in all releases	TC-4337, TC-4346, TC-4349 , TC-4322 	Automated	"25.1.1 Release was performed.  Smoke testing discovered a problem at 3:38am ET/2025-02-13

Exception Hash: ED0E0032C0700DE16BA15FD731A7AA2EEF01E5E4 Exception Type: System.NullReferenceException Exception Time: 2/13/2025 8:25:33 AM Description: Object reference not set to an instance of an object
Scheduled Reports found to be failing:

index=""grc-elm-t360_prod"" ""Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces""