window.reportData = {
  "dateRange": "Sprint 26.1.2",
  "generated": "2026-01-12 16:52:29",
  "summary": {
    "total": 20,
    "tadComplete": 15,
    "tsComplete": 11,
    "bothComplete": 11,
    "missingTad": 1,
    "missingTs": 5,
    "tadNA": 4,
    "tsNA": 4,
    "tadApplicable": 16,
    "tsApplicable": 16,
    "tadPct": 93.75,
    "tsPct": 68.75,
    "bothPct": 55.00000000000001,
    "missingTadPct": 5.0,
    "missingTsPct": 25.0,
    "tadNAPct": 20.0,
    "tsNAPct": 20.0
  },
  "teams": {
    "Matrix": {
      "total": 3,
      "tadComplete": 2,
      "tsComplete": 0,
      "bothComplete": 0,
      "tadNA": 0,
      "tsNA": 0,
      "tadApplicable": 3,
      "tsApplicable": 3,
      "missingTad": 1,
      "missingTs": 3,
      "tadPct": 66.66666666666666,
      "tsPct": 0.0,
      "issues": [
        {
          "key": "GET-66038",
          "summary": "Enable Full CRUD Support in T360.Scheduler.API ",
          "type": "Story",
          "status": "Re-finement",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": false,
          "totalPrs": 1,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-66035",
          "summary": " Implement Angular Scheduler List Component with Delete and Trigger Actions",
          "type": "Story",
          "status": "Re-finement",
          "sprint": "No Sprint",
          "tadFound": false,
          "tsFound": false,
          "totalPrs": 0,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-66112",
          "summary": "Enable Seamless SSO from T360 to Scheduler Angular ",
          "type": "Story",
          "status": "Re-finement",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": false,
          "totalPrs": 1,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        }
      ]
    },
    "T360 Chargers": {
      "total": 4,
      "tadComplete": 0,
      "tsComplete": 0,
      "bothComplete": 0,
      "tadNA": 4,
      "tsNA": 4,
      "tadApplicable": 0,
      "tsApplicable": 0,
      "missingTad": 0,
      "missingTs": 0,
      "tadPct": 0,
      "tsPct": 0,
      "issues": [
        {
          "key": "GET-65988",
          "summary": "[T360 Modernization] UUID: E100F102 - MinimalApi Template Enhancement",
          "type": "Story",
          "status": "Refined",
          "sprint": "No Sprint",
          "tadFound": false,
          "tsFound": false,
          "totalPrs": 0,
          "tadNA": true,
          "tadNAComment": "This is an enabler story to prepare the templates for the actual modernization implementation. Hence, this does not require TAD and TS.",
          "tsNA": true,
          "tsNAComment": "Test Strategy N/A because TAD is N/A"
        },
        {
          "key": "GET-65992",
          "summary": "[T360 Modernization]UUID: E100F104 - Workspace",
          "type": "Story",
          "status": "Refined",
          "sprint": "No Sprint",
          "tadFound": false,
          "tsFound": false,
          "totalPrs": 0,
          "tadNA": true,
          "tadNAComment": "This is an enabler story to prepare the templates for the actual modernization implementation. Hence, this does not require TAD and TS.",
          "tsNA": true,
          "tsNAComment": "Test Strategy N/A because TAD is N/A"
        },
        {
          "key": "GET-65984",
          "summary": "[T360 Modernization] UUID: E100F103 - Web API",
          "type": "Story",
          "status": "Refined",
          "sprint": "No Sprint",
          "tadFound": false,
          "tsFound": false,
          "totalPrs": 0,
          "tadNA": true,
          "tadNAComment": "This is an enabler story to prepare the templates for the actual modernization implementation. Hence, this does not require TAD and TS.",
          "tsNA": true,
          "tsNAComment": "Test Strategy N/A because TAD is N/A"
        },
        {
          "key": "GET-65982",
          "summary": "[T360 Modernization] UUID: E100F100: DDD Template Alignment",
          "type": "Story",
          "status": "Refined",
          "sprint": "No Sprint",
          "tadFound": false,
          "tsFound": false,
          "totalPrs": 0,
          "tadNA": true,
          "tadNAComment": "This is an enabler story to prepare the templates for the actual modernization implementation. Hence, this does not require TAD and TS.",
          "tsNA": true,
          "tsNAComment": "Test Strategy N/A because TAD is N/A"
        }
      ]
    },
    "T360 Mavericks": {
      "total": 4,
      "tadComplete": 4,
      "tsComplete": 4,
      "bothComplete": 4,
      "tadNA": 0,
      "tsNA": 0,
      "tadApplicable": 4,
      "tsApplicable": 4,
      "missingTad": 0,
      "missingTs": 0,
      "tadPct": 100.0,
      "tsPct": 100.0,
      "issues": [
        {
          "key": "GET-63004",
          "summary": "Performance - Overall degradation on Search All Invoices (Beta) page across all filters",
          "type": "Bug",
          "status": "Re-finement",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 6,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-22679",
          "summary": "User is able to set same time period on editing an AFA.",
          "type": "Bug",
          "status": "Refined",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 2,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-57743",
          "summary": "AI Console: UI Updates",
          "type": "Story",
          "status": "Refined",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 2,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-22600",
          "summary": "The AFA amount isn't properly adjusted when an ITP adjustment is applied to the invoice.",
          "type": "Bug",
          "status": "Refined",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 2,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        }
      ]
    },
    "T360 Vanguards": {
      "total": 3,
      "tadComplete": 3,
      "tsComplete": 2,
      "bothComplete": 2,
      "tadNA": 0,
      "tsNA": 0,
      "tadApplicable": 3,
      "tsApplicable": 3,
      "missingTad": 0,
      "missingTs": 1,
      "tadPct": 100.0,
      "tsPct": 66.66666666666666,
      "issues": [
        {
          "key": "GET-64554",
          "summary": "Invoice AI - Citations - Focus on Line Items ",
          "type": "Story",
          "status": "Refined",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 3,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-62669",
          "summary": "Invoice AI - Clicking the Invoice& Line Item ID",
          "type": "Story",
          "status": "Refined",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 2,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-64705",
          "summary": "Invoice AI - Payloads (Budgets & Adjustments)- AI Console & BFF",
          "type": "Story",
          "status": "Re-finement",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": false,
          "totalPrs": 1,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        }
      ]
    },
    "Nexus": {
      "total": 3,
      "tadComplete": 3,
      "tsComplete": 3,
      "bothComplete": 3,
      "tadNA": 0,
      "tsNA": 0,
      "tadApplicable": 3,
      "tsApplicable": 3,
      "missingTad": 0,
      "missingTs": 0,
      "tadPct": 100.0,
      "tsPct": 100.0,
      "issues": [
        {
          "key": "GET-61103",
          "summary": "LC part 1: Correct Token Claims and Session Handling for Network Admin Role Assignment and Passport Demo Readiness",
          "type": "Story",
          "status": "Refined",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 2,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-60909",
          "summary": "Performance - Degradation observed while clicking on Search All Invoices Beta page, and last page of pagination",
          "type": "Bug",
          "status": "Refined",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 3,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-44294",
          "summary": "   TEC-419925: New UI: Export to Excel does not work on the Select Budget Template page ",
          "type": "Bug",
          "status": "Refined",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 2,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        }
      ]
    },
    "T360 ICD Chubb": {
      "total": 3,
      "tadComplete": 3,
      "tsComplete": 2,
      "bothComplete": 2,
      "tadNA": 0,
      "tsNA": 0,
      "tadApplicable": 3,
      "tsApplicable": 3,
      "missingTad": 0,
      "missingTs": 1,
      "tadPct": 100.0,
      "tsPct": 66.66666666666666,
      "issues": [
        {
          "key": "GET-63651",
          "summary": "Claim Authority Bypass Logic at Approval (Popup Suppression)",
          "type": "Story",
          "status": "Refined",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": false,
          "totalPrs": 2,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-62628",
          "summary": "Restrict Lead Timekeeper Rates if greater than $0 - Service",
          "type": "Story",
          "status": "Refined",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 2,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-62062",
          "summary": "Enable Re-scoring of Predictive Insights for Awaiting Send / Sent to AI Scored Matters",
          "type": "Story",
          "status": "Refined",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 2,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        }
      ]
    }
  }
};