window.reportData = {
  "dateRange": "Sprint 26.1.1",
  "generated": "2026-01-12 17:19:56",
  "summary": {
    "total": 23,
    "tadComplete": 21,
    "tsComplete": 19,
    "bothComplete": 19,
    "missingTad": 0,
    "missingTs": 2,
    "tadNA": 2,
    "tsNA": 2,
    "tadApplicable": 21,
    "tsApplicable": 21,
    "tadPct": 100.0,
    "tsPct": 90.47619047619048,
    "bothPct": 82.6086956521739,
    "missingTadPct": 0.0,
    "missingTsPct": 8.695652173913043,
    "tadNAPct": 8.695652173913043,
    "tsNAPct": 8.695652173913043
  },
  "teams": {
    "Nexus": {
      "total": 4,
      "tadComplete": 4,
      "tsComplete": 4,
      "bothComplete": 4,
      "tadNA": 0,
      "tsNA": 0,
      "tadApplicable": 4,
      "tsApplicable": 4,
      "missingTad": 0,
      "missingTs": 0,
      "tadPct": 100.0,
      "tsPct": 100.0,
      "issues": [
        {
          "key": "GET-50527",
          "summary": "INC3102287 - PRB0057529 Analyze and create missing index suggested by DPA",
          "type": "Story",
          "status": "To Verify",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 3,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-64300",
          "summary": "CA LegalCollaborator: Enable Corporate Users to Create Case Assessments Without Role Misassignment and Populate CA Manager in Payload",
          "type": "Story",
          "status": "To Verify",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 3,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-63638",
          "summary": "LegalCollaborator: Cancel or Update Case Assessment on Company/Panel/TK Change when CA exists prior",
          "type": "Story",
          "status": "Code Complete",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 4,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-3928",
          "summary": "TEC-301935 - CNA High Priority: Performance: Invoice Search Page Processed - Search Slowness",
          "type": "Bug",
          "status": "To Verify",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 4,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        }
      ]
    },
    "Matrix": {
      "total": 4,
      "tadComplete": 4,
      "tsComplete": 2,
      "bothComplete": 2,
      "tadNA": 0,
      "tsNA": 0,
      "tadApplicable": 4,
      "tsApplicable": 4,
      "missingTad": 0,
      "missingTs": 2,
      "tadPct": 100.0,
      "tsPct": 50.0,
      "issues": [
        {
          "key": "GET-64544",
          "summary": "Migrate Scheduling Workflows from JAMS to Modern Scheduler Platform",
          "type": "Story",
          "status": "To Verify",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 7,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-66018",
          "summary": "Scheduler UI \u2013 CI/CD Setup for NA (Containerized) and EU (TeamCity/Octopus)",
          "type": "Story",
          "status": "In Progress",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": false,
          "totalPrs": 2,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-64548",
          "summary": "T360.Scheduler.API \u2013 CI/CD Setup for NA (Containerized) and EU (TeamCity/Octopus)",
          "type": "Story",
          "status": "In Progress",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": false,
          "totalPrs": 1,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-66026",
          "summary": "Introduce \u201cJobs Scheduler\u201d Menu in T360 with Network & Permission-Based Access Control",
          "type": "Story",
          "status": "To Verify",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 5,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        }
      ]
    },
    "T360 ICD Chubb": {
      "total": 4,
      "tadComplete": 4,
      "tsComplete": 4,
      "bothComplete": 4,
      "tadNA": 0,
      "tsNA": 0,
      "tadApplicable": 4,
      "tsApplicable": 4,
      "missingTad": 0,
      "missingTs": 0,
      "tadPct": 100.0,
      "tsPct": 100.0,
      "issues": [
        {
          "key": "GET-62060",
          "summary": "Predictive Insights: Rescoring a matter in bulk via data exchange",
          "type": "Story",
          "status": "To Verify",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 4,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-58776",
          "summary": "Claim Authority Exclusion Secure Action & Permission Setup",
          "type": "Story",
          "status": "To Verify",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 5,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-22095",
          "summary": "TEC-369708: Chubb Group Claims: ITP rule not working correctly in prod",
          "type": "Bug",
          "status": "To Verify",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 3,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-58925",
          "summary": "Affiliated Vendor can associate one to many on matters - data exchange",
          "type": "Story",
          "status": "Code Complete",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 5,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        }
      ]
    },
    "T360 Chargers": {
      "total": 3,
      "tadComplete": 1,
      "tsComplete": 1,
      "bothComplete": 1,
      "tadNA": 2,
      "tsNA": 2,
      "tadApplicable": 1,
      "tsApplicable": 1,
      "missingTad": 0,
      "missingTs": 0,
      "tadPct": 100.0,
      "tsPct": 100.0,
      "issues": [
        {
          "key": "GET-65980",
          "summary": "[T360 Modernization]UUID:UUID: E100F100S100 - Upgrade DDD Template to .NET 9.0",
          "type": "Story",
          "status": "In Progress",
          "sprint": "No Sprint",
          "tadFound": false,
          "tsFound": false,
          "totalPrs": 1,
          "tadNA": true,
          "tadNAComment": "Discussed in Refinement, As this is an Enabler story TAD is not applicable.",
          "tsNA": true,
          "tsNAComment": "Test Strategy N/A because TAD is N/A"
        },
        {
          "key": "GET-65986",
          "summary": "[T360 Modernization] UUID: E100F101-CQRS Template Alignment",
          "type": "Story",
          "status": "In Progress",
          "sprint": "No Sprint",
          "tadFound": false,
          "tsFound": false,
          "totalPrs": 1,
          "tadNA": true,
          "tadNAComment": "This is a Enabler story, so TAD not Applicable.",
          "tsNA": true,
          "tsNAComment": "Test Strategy N/A because TAD is N/A"
        },
        {
          "key": "GET-65633",
          "summary": "[Document Modernization]- Dual _Write off ",
          "type": "Story",
          "status": "To Verify",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 11,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        }
      ]
    },
    "T360 Mavericks": {
      "total": 4,
      "tadComplete": 4,
      "tsComplete": 4,
      "bothComplete": 4,
      "tadNA": 0,
      "tsNA": 0,
      "tadApplicable": 4,
      "tsApplicable": 4,
      "missingTad": 0,
      "missingTs": 0,
      "tadPct": 100.0,
      "tsPct": 100.0,
      "issues": [
        {
          "key": "GET-60431",
          "summary": "Update Matter AI label",
          "type": "Story",
          "status": "To Verify",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 3,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-61996",
          "summary": "[UAT/TST] The spinner keeps on loading while searching with multiple special symbols in the query",
          "type": "Bug",
          "status": "To Verify",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 3,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-62132",
          "summary": "Correct AI console Selections issues",
          "type": "Story",
          "status": "In Progress",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 5,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-62748",
          "summary": "AI console: Add UI for adding AI methods",
          "type": "Story",
          "status": "In Progress",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 3,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        }
      ]
    },
    "T360 Vanguards": {
      "total": 4,
      "tadComplete": 4,
      "tsComplete": 4,
      "bothComplete": 4,
      "tadNA": 0,
      "tsNA": 0,
      "tadApplicable": 4,
      "tsApplicable": 4,
      "missingTad": 0,
      "missingTs": 0,
      "tadPct": 100.0,
      "tsPct": 100.0,
      "issues": [
        {
          "key": "GET-64677",
          "summary": "Citations - Convert Citations to Interactive Links with Line Item Reference Panel",
          "type": "Story",
          "status": "To Verify",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 4,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-62908",
          "summary": "Invoice AI - Payloads (Budgets & Adjustments)- T360 Web API & Cannonical",
          "type": "Story",
          "status": "Code Complete",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 6,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-64675",
          "summary": "Citations - Transform Payload Citations into Numbered References",
          "type": "Story",
          "status": "Code Complete",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 7,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        },
        {
          "key": "GET-56987",
          "summary": "ASVS-Verify that any printable Unicode character, including language neutral characters such as spaces and Emojis are permitted in passwords.",
          "type": "Story",
          "status": "To Verify",
          "sprint": "No Sprint",
          "tadFound": true,
          "tsFound": true,
          "totalPrs": 8,
          "tadNA": false,
          "tadNAComment": null,
          "tsNA": false,
          "tsNAComment": null
        }
      ]
    }
  }
};